//LOGIN
export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//REGISTER
export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

//UPLOAD
export const UPLOAD = "UPLOAD"
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
export const UPLOAD_FAILURE = "UPLOAD_FAILURE"

export const LOGOUT = "LOGOUT"
export const REINSTATE_STATE = "REINSTATE_STATE"